### ISSUE TITLE
Region ID

### ISSUE THREAD

**Issue by zmey777711** [yourmnbbn/tiny-csgo-server#10]
How i can change server region id, it always give -1

```
<appid>730</appid>
<gamedir>csgo</gamedir>
<region>-1</region>
<secure>true</secure>
<lan>false</lan>
<gameport>27015</gameport>

```

**Comment by yourmnbbn** [comment]
Region can be set by `ISteamGameServer::SetRegion`. The following code is copied from isteamgameserver.h.
```cpp
/// Region identifier.  This is an optional field, the default value is empty, meaning the "world" region
virtual void SetRegion( const char *pszRegion ) = 0;
```
You can set it here.
https://github.com/yourmnbbn/tiny-csgo-server/blob/08243f2a2457827ff8b0c795e3eeb699aa98ce0c/src/server.hpp#L252-L264

**Comment by zmey777711** [comment]
Very thanks! All works!
