### ISSUE TITLE
Servers online

### ISSUE THREAD

**Issue by ArtemSushkov** [yourmnbbn/tiny-csgo-server#11]
Can u add the feature like in fakequeries (add fake players) to control online in the any tiny-server?

**Comment by yourmnbbn** [comment]
Online players count can't be easily controlled by server query in the Internet tab of the browser, which is what most of the people want to achieve. So make a variable players count is meaningless.

**Comment by zmey777711** [comment]
In your plugin 'fakequeries' its works good! This plugin too writed on C++.
Maybe you have actual fixes except +1 player with tiny-csgo-client? :(

And I would like to take this opportunity to thank you for your work.

**Comment by yourmnbbn** [comment]
Fakequeries extension can't have an effect on the online players in Internet tab neither. If you only care about faking players in other parts like favorite or history tab, you can simply change the following part:
`CONFIG_HANDLE_QUERY_BY_STEAM = 0`
https://github.com/yourmnbbn/tiny-csgo-server/blob/08243f2a2457827ff8b0c795e3eeb699aa98ce0c/src/common/info_const.hpp#L11
SERVER_NUM_CLIENTS to whatever you want
https://github.com/yourmnbbn/tiny-csgo-server/blob/08243f2a2457827ff8b0c795e3eeb699aa98ce0c/src/common/info_const.hpp#L19

**Comment by zmey777711** [comment]
Maybe I can help to you with it for collect data of other server or more
help???
I attach screen where server have 646 some servers with 64 or 65 online ,
how they doing it?
Your plugin is very close to it, can I help repair it for online showing in
internet tab??? ;(

[image: изображение.png]


вс, 5 февр. 2023 г. в 16:56, yourmnbbn ***@***.***>:

**Comment by zmey777711** [comment]
Console logs from trying to connect, its very very fast answer (<1 sec)

CS_App_Lifetime_Gamestats: Recording ServerBrowserInternet
Host_WriteConfiguration: Wrote cfg/config.cfg
Connecting to public(45.32.122.194:28022) ...
Connecting to public(46.174.49.219:27015) ...
Server using 'public' lobbies, requiring pw no, lobby id ffffffffffffffff
#Valve_Reject_Server_Full

вс, 5 февр. 2023 г. в 19:08, Artem S ***@***.***>:

**Comment by zmey777711** [comment]
They havent first message about lobbies and every time "
Host_WriteConfiguration: Wrote cfg/config.cfg "

вс, 5 февр. 2023 г. в 19:11, Artem S ***@***.***>:

**Comment by yourmnbbn** [comment]
Fake online can be manipulated right now. Please refer to https://github.com/yourmnbbn/csgo-fake-server for more information.
