### ISSUE TITLE
 fatal error: isteamgamecoordinator.h: No such file or directory

### ISSUE THREAD

**Issue by gaalos** [yourmnbbn/tiny-csgo-server#14]
Hi
I'm on deb 11 and i got this error :

[ 14%] Building CXX object CMakeFiles/tiny-csgo-server.dir/sv-main.cpp.o
In file included from /root/fake/tiny-csgo-server/sv-main.cpp:2:
/root/fake/tiny-csgo-server/src/GCClient.hpp:11:10: fatal error: isteamgamecoordinator.h: No such file or directory
11 | #include <isteamgamecoordinator.h>
| ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/tiny-csgo-server.dir/build.make:76: CMakeFiles/tiny-csgo-server.dir/sv-main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/tiny-csgo-server.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by yourmnbbn** [comment]
Make sure you've downloaded the right hl2sdk, it's csgo branch not sdk2013 or some others.

**Comment by gaalos** [comment]
@yourmnbbn your right i did not change my branch x')

**Comment by gaalos** [comment]
@yourmnbbn Still have issues 

 git branch
* csgo
  sdk2013


Here you have my build.sh
#!/bin/bash

HL2SDK_DIR="/root/fake/hl2sdk"
ASIO_DIR="/root/fake/asio/asio"

cmake -DCMAKE_BUILD_TYPE=Release -DHL2SDK-CSGO:PATH=$HL2SDK_DIR -DASIO-SRC:PATH=$ASIO_DIR -DEXECUTABLE_OUTPUT_PATH=$PWD/build/Release
make


but still have this issue 
In file included from /root/fake/tiny-csgo-server/sv-main.cpp:2:
/root/fake/tiny-csgo-server/src/GCClient.hpp:11:10: fatal error: isteamgamecoordinator.h: No such file or directory
   11 | #include <isteamgamecoordinator.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by yourmnbbn** [comment]
Then you still got the wrong sdk. Manually check if that file exist in the sdk folder.

**Comment by gaalos** [comment]
@yourmnbbn  you'r right ! i don't undrestand why my files did not changes.
