### ISSUE TITLE
-mirror problem

### ISSUE THREAD

**Issue by toorisrael** [yourmnbbn/tiny-csgo-server#16]
Hi.
When using -mirror option and running multiple (10+) servers with VAC enabled I get on most of them:
Auth response: 5(VAC has been unable to perform anti-cheat checks on this user)
Without -mirror, the same servers work fine.
I'm not using tiny-steam-client, and I've read disclaimer about disabling VAC, just wanted to notice possible bug with -mirror option.
Also, when you disable VAC, you can of course spoof it in A2S_INFO, however when player selects showing only secured servers, it won't show servers with spoofed VAC - Valve has changed this behavior some time ago.

**Comment by yourmnbbn** [comment]
Hello, I've tested vac secured tiny csgo server with option -mirror to authenticate players, but haven't encountered the vac timeout. Actually tiny steam client can easily authenticate players to vac enabled tiny csgo server with the following two lines commented. Such behavior can't be 100% reproduced so I think you can try to test it with modified tiny steam client to see if there is still problem with -mirror.
https://github.com/yourmnbbn/tiny-steam-client/blob/dff918d9c23e86c516405a18c15d5d59151733c6/src/SteamClient.hpp#L443
https://github.com/yourmnbbn/tiny-steam-client/blob/dff918d9c23e86c516405a18c15d5d59151733c6/src/SteamClient.hpp#L407

>Also, when you disable VAC, you can of course spoof it in A2S_INFO, however when player selects showing only secured servers, it won't show servers with spoofed VAC - Valve has changed this behavior some time ago.

I'll update tiny steam client and the fake server documentation to support vac fake server when I have time.

**Comment by toorisrael** [comment]
Well, it turns out it has nothing to do with "-mirror" option, just a bad luck it happened with a not w/o this option.
After more tests it just happens randomly, also with older versions, I think this problem is unrelated to this project.
