### ISSUE TITLE
compiled filed 

### ISSUE THREAD

**Issue by szogun1910** [yourmnbbn/tiny-csgo-server#21]
`CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error in CMakeLists.txt:
  Target "tiny-csgo-server" requires the language dialect "CXX20" (with
  compiler extensions).  But the current compiler "GNU" does not support
  this, or CMake does not know the flags to enable it.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
[ 14%] Building CXX object CMakeFiles/tiny-csgo-server.dir/sv-main.cpp.o
c++: error: unrecognized command line option ‘-fcoroutines’
CMakeFiles/tiny-csgo-server.dir/build.make:75: recipe for target 'CMakeFiles/tiny-csgo-server.dir/sv-main.cpp.o' failed
make[2]: *** [CMakeFiles/tiny-csgo-server.dir/sv-main.cpp.o] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/tiny-csgo-server.dir/all' failed
make[1]: *** [CMakeFiles/tiny-csgo-server.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by wickedroid** [comment]
gcc version 10 / You should install the corresponding version of gcc-multilib to compile the 32bit application and it would work
