### ISSUE TITLE
Client get "Server is running an older version" error when trying to connect.

### ISSUE THREAD

**Issue by AidarSource** [yourmnbbn/tiny-csgo-server#4]
According to Steam API it works fine - https://api.steampowered.com/IGameServersService/GetServerList + steamapikey + ip
But you can't connect to it and it won't show in internet tab, can't add sv to favorites either

**Comment by yourmnbbn** [comment]
>But you can't connect to it

This server is not for connecting.

>it won't show in internet tab

Checked in game browser again and it works fine and servers are shown on the internet tab. From the tiny server console if you keep receiving messages from random IP address then it is working properly. There are many reasons you may not see it in the browser. Even sometimes the authentic server would disappear from your browser either.

**Comment by AidarSource** [comment]
> > But you can't connect to it
> 
> This server is not for connecting.
> 
> > it won't show in internet tab
> 
> Checked in game browser again and it works fine and servers are shown on the internet tab. From the tiny server console if you keep receiving messages from random IP address then it is working properly. There are many reasons you may not see it in the browser. Even sometimes the authentic server would disappear from your browser either.

hmm, how is it happening:D
My server: 138.2.165.228:27016
If I check it by SteamAPI, it works. https://api.steampowered.com/IGameServersService/GetServerList/v1/?key=YOURSTEAMAPIKEY&filter=addr\138.2.165.228
But If I try to add it to favorites tab in csgo - I can't do it, or find by tags in Internet tab I can't find it.

Server running logs is fine too, only one warning: `Warning: failed to init SDL thread priority manager: SDL not found`.

Maybe there are problems with A2S_INFO?

**Comment by AidarSource** [comment]
> From the tiny server console if you keep receiving messages from random IP address then it is working properly.

and yeah, I can't see connection from tiny-csgo-server console

**Comment by AidarSource** [comment]
I think this is the problem. In SteamAPI response tiny-csgo-server returns `"product":"valve"` when typical csgo server returns `"product":"csgo"`. @yourmnbbn can it be the case?
let me try to fix it to product "csgo", wait a minute

**Comment by yourmnbbn** [comment]
>But If I try to add it to favorites tab in csgo - I can't do it, or find by tags in Internet tab I can't find it.

If you create authentic server in the same server you probably won't find it too. Sometimes I can't find my own servers either(not the fake ones), it depends and it does happen sometimes. Most of the time it's because of your internet environment. 

>Maybe there are problems with A2S_INFO?

No. This isn't related to this. 

>and yeah, I can't see connection from tiny-csgo-server console

The console will print out each message it has received, but most of them are A2S queries. This server will reject any connections.

>I think this is the problem. In SteamAPI response tiny-csgo-server returns "product":"valve" when typical csgo server returns "product":"csgo". @yourmnbbn can it be the case?

No.

**Comment by AidarSource** [comment]
redirect thing not working too for me

**Comment by yourmnbbn** [comment]
Redirecting is using CSGO build-in implementation. But it has a flaw, since csgo requires server reservation id from GC, redirecting may still use the previous requested reservation id which doesn't belong to the new server and will cause `#VALVE_REJECT_FROM_LOBBY` error when connecting. It's not recommended to use redirecting unless you write your own router to the server.

**Comment by AidarSource** [comment]
ohhh, shit. How I didn't notice this in game console:
`Server is running an older version, client version 13846, server version 13837`
but why??
I run server with proper configs - `tiny-csgo-server.exe -port 27016 -version 1.38.4.6 -gslt MYTOKEN`

**Comment by yourmnbbn** [comment]
>Server is running an older version, client version 13846, server version 13837

This is because of the following code. You can change this to the updated version. I'll fix this when I have time.
https://github.com/yourmnbbn/tiny-csgo-server/blob/52b9fca511e39daffbe277816c8f863d05a4dc79/src/server.hpp#L214

**Comment by AidarSource** [comment]
thanks! now server working in my localhost.

But still problems in my VPS, server not responding at all. I can't connect to server with `connect IP` in game console, it throws `Retrying public . . . (IP)` error

**Comment by yourmnbbn** [comment]
Check if the udp protocol of the port you're using is blocked by the server's firewall.

**Comment by AidarSource** [comment]
> Check if the udp protocol of the port you're using is blocked by the server's firewall.

Opened ports needed for csgo, but still same. I'll try some more with ports, I think its the case
![image](https://user-images.githubusercontent.com/34319725/198885863-018d092d-7bd3-4fc8-b8cc-02f22f74c421.png)

**Comment by AidarSource** [comment]
yeah, it was port issue. Thanks a lot!

**Comment by yourmnbbn** [comment]
Commit [c993230](https://github.com/yourmnbbn/tiny-csgo-server/commit/c99323035653c13452758f3400d62102e0473ce8) has fixed the error `Server is running an older version`. Close this as completed.
