### ISSUE TITLE
I can't log in to the redirect server

### ISSUE THREAD

**Issue by 0-BuTaJIuK-0** [yourmnbbn/tiny-csgo-server#7]
tiny-csgo-server (27777)
csgo server (27016)

Client:
**connect IP:27777**
ChangeGameUIState: CSGO_GAME_UI_STATE_MAINMENU -> CSGO_GAME_UI_STATE_LOADINGSCREEN
CS_App_Lifetime_Gamestats: Recording ServerBrowserFavorites 
Connecting to public(IP:27777) ...
Server using 'public' lobbies, requiring pw no, lobby id ffffffffffffffff
Connecting to public(IP:27016) ...
Server using 'public' lobbies, requiring pw no, lobby id ffffffffffffffff
#Valve_Reject_Connect_From_Lobby
**** Unable to localize '#GenericConfirmText_Label' on panel descendant of 'PopupManager'
ChangeGameUIState: CSGO_GAME_UI_STATE_LOADINGSCREEN -> CSGO_GAME_UI_STATE_MAINMENU
ChangeGameUIState: CSGO_GAME_UI_STATE_MAINMENU -> CSGO_GAME_UI_STATE_MAINMENU

MY server:
RejectConnection: IP:27005 - #Valve_Reject_Connect_From_Lobby

At the same time, I can just log in to the server (without redirect) **connect IP:27016**

**Comment by yourmnbbn** [comment]
For solution to redirecting not working please refer to [this issue](https://github.com/yourmnbbn/tiny-csgo-server/issues/5).

**Comment by 0-BuTaJIuK-0** [comment]
@yourmnbbn senk, all ok
