### ISSUE TITLE
Fake players are not displayed

### ISSUE THREAD

**Issue by 0-BuTaJIuK-0** [yourmnbbn/tiny-csgo-server#8]
![image](https://user-images.githubusercontent.com/44897927/213019583-4a0335f7-a6e2-44cc-a278-b4105747832b.png)
```
//Configs
_DECL_CONST CONFIG_HANDLE_QUERY_BY_STEAM = 1;

//Server information
_DECL_CONST SERVER_NAME = "Tiny csgo server";
_DECL_CONST SERVER_MAP = "de_tinycsgomap";
_DECL_CONST SERVER_GAME_FOLDER = "csgo";
_DECL_CONST SERVER_DESCRIPTION = "Counter-Strike: Global Offensive";
_DECL_CONST SERVER_APPID = 730;
_DECL_CONST SERVER_NUM_CLIENTS = 10;
_DECL_CONST SERVER_MAX_CLIENTS = 12;
_DECL_CONST SERVER_NUM_FAKE_CLIENTS = 8;
_DECL_CONST SERVER_TYPE = 'd';
_DECL_CONST SERVER_OS = 'w';
_DECL_CONST SERVER_PASSWD_NEEDED = 0;
_DECL_CONST SERVER_VAC_STATES = 1;
_DECL_CONST SERVER_TAG = "pure, vac, tiny-csgo-server";
_DECL_CONST SERVER_DCFRIENDSREQD = 0;
_DECL_CONST SERVER_VALVE_OFFICIAL = 0;
```

**Comment by 0-BuTaJIuK-0** [comment]
Without fake clients, everything shows

**Comment by 0-BuTaJIuK-0** [comment]
![image](https://user-images.githubusercontent.com/44897927/213022136-bc5cc95e-8c1c-4297-ab94-3546515e7095.png)

**Comment by yourmnbbn** [comment]
To fake online players count, you have to authenticate players, whether by using tiny client connection or implementing authentication process in the tiny server yourself.

**Comment by 0-BuTaJIuK-0** [comment]
And then what is responsible for _DECL_CONST SERVER_NUM_FAKE_CLIENTS = 8;

**Comment by yourmnbbn** [comment]
This is only valid when you set `CONFIG_HANDLE_QUERY_BY_STEAM = 0`. The tiny server will build A2S response itself instead of letting steamclient library do the job. And this value will only affect player number outside of the internet tab of the browser. When client requests server lists(which will be listed in the Internet tab of the browser) from GC, GC responses with the player count which is counted by GC itself(through player app ticket authentication), not the one that server reported to it.

**Comment by 0-BuTaJIuK-0** [comment]
Senk
Interestingly, it is displayed normally in favorites

**Comment by 0-BuTaJIuK-0** [comment]
I understood correctly. It is not possible to emulate players on the "Internet". Just somehow log in from your accounts. And if you create 1 server (with your clients) and somehow redirect traffic to other servers?

**Comment by 0-BuTaJIuK-0** [comment]
![image](https://user-images.githubusercontent.com/44897927/213299766-ca9cdecd-ef1b-46f6-bfee-d19374ac396f.png)
![image](https://user-images.githubusercontent.com/44897927/213299814-3c924ee0-00f9-4b74-9cd8-a58fb5fe3ce9.png)
Do they really have so many accounts? 64 in each)

**Comment by 0-BuTaJIuK-0** [comment]
![image](https://user-images.githubusercontent.com/44897927/213300112-d6393511-f244-444a-9b14-c4fc3ab03367.png)
Here is something similar to the truth, but each has 4 users with the same name

**Comment by yourmnbbn** [comment]
>And still, I didn't quite understand what the parameter is responsible for CONFIG_HANDLE_QUERY_BY_STEAM )))))

Look at the code where it's referenced and you'll understand.

>It is not possible to emulate players on the "Internet"

Not true, it's possible. Those fake servers are implemented in javascript with the help of [this library](https://github.com/DoctorMcKay/node-steam-user) which contains all the interfaces you need to implementing your own fake servers like them. And you can also use this tiny server and use that library to implement authentication.

**Comment by 0-BuTaJIuK-0** [comment]
Thank you for answering in detail)
